# Generated by Django 2.0.5 on 2018-05-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('neighbors', models.CharField(max_length=500)),
                ('arrival_popularity', models.FloatField()),
                ('departure_popularity', models.FloatField()),
            ],
        ),
    ]
